cloudcannon:
  data: true

sass:
  sass_dir: _sass
  style: compressed

uploads_dir: /assets/images

plugins:
  - jekyll-responsive-image
  - jekyll-feed
  - jekyll-webp
  - jekyll-sitemap

# Plugin configurations
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/", "assets/images", "/assets/images/srcset"]
  nested: true
  regenerate: false

# Configuration of the compress_html layout
compress_html:
  comments: all  

# Background classes for the sections
background_classes:
  - bg-primary
  - bg-secondary
  - bg-accent
  - bg-reset

_comments:
  font_family_embed_code_block: Load the Google Fonts and Fontawesome scripts here
  body_font_size_number: "Please specify 'rem' or 'px'"
  body_font_family: For all paragraphs, links and buttons
  heading_font_family: For all headings, subtitles and section intros

