general:
  site_url:
  address:
  email:
  phone:
  facebook_url: 'https://facebook.com'
  instagram_url: 'https://instagram.com'
  instagram_handle: '@yourhandle'
  twitter_url: 'https://twitter.com'
  twitter_handle: '@yourhandle'
  youtube_url: 'https://youtube.com'
  github_url: 'https://github.com'
  linkedin_url: 'https://linkedin.com'
  snapchat_url: 'https://snapchat.com'
  stackoverflow_url: 'https://stackoverflow.com'
branding:
  site_title: My Site
  nav_logo_image:
  footer_logo_image:
  preview_image:
theme_settings:
  primary_color: "#aaa"
  secondary_color: "#000"
  accent_color: "#F10CBA"
  shade_color: "#f2f2f2"
  complementary_color: "2f2f2f"
  font_family_embed_code_block:
  body_font_family: "arial, sans-serif"
  heading_font_family: "times new roman, sans-serif"
  body_font_size_number: 1rem
  line_spacing_number:
seo:
  site_description_text:
  keywords: